# Bot Settings
bot-token: Please-Replace-Here-To-Bot-Token #botのトークンをここに書いてください

# Server Settings
server-id: 0 #Server-ID
server-channel-text: 0 #Alarm-Channel(Text)-ID
server-channel-voice: 0 #Alarm-Channel(Voice)-ID

# Dev Settings
dev-debug-mode: false #debug-mode(true|false)
dev-channel-text: 0 #Dev-Alarm-Channel(Text)-ID
dev-channel-voice: 0 #Dev-Alarm-Channel(Text)-ID

# Template
# {role}: 特定の時限のロールID
# {weekday}: 曜日
# {time}: 時限
template: "<@&{role}> {weekday}曜日 {time}限 の開始時刻です。出席確認をしてください。"

# Messages
playing: "起きろ起きろ起きろ起きろ起きろ起きろ起きろ起きろ起きろ起きろ"
stopped: "再生を停止しました。"
disconnected: "ボイスチャンネルから切断しました。"

## Role ID
# 月曜日
monday-1: 0
monday-2: 0
monday-3: 0
monday-4: 0
monday-5: 0

# 火曜日
tuesday-1: 0
tuesday-2: 0
tuesday-3: 0
tuesday-4: 0
tuesday-5: 0

# 水曜日
wednesday-1: 0
wednesday-2: 0
wednesday-3: 0
wednesday-4: 0
wednesday-5: 0

# 木曜日
thursday-1: 0
thursday-2: 0
thursday-3: 0
thursday-4: 0
thursday-5: 0

# 金曜日
friday-1: 0
friday-2: 0
friday-3: 0
friday-4: 0
friday-5: 0

# デバッグ用
debug-role: 0